version: "3.8"

services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./env:/env
      - ./.env:/.env
      - ./postgres/dump_09032023.sql:/docker-entrypoint-initdb.d/dump_09032023.sql
      - postgres_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./env/postgres/.env
      - ./.env

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
    volumes:
      - ./env:/env
      - ./.env:/.env
      - elasticsearch_data:/usr/share/elasticsearch-one/data
    expose:
      - ${ELASTIC_PORT}
    env_file:
      - ./env/elasticsearch/.env
      - ./.env

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./env:/env
      - ./.env:/.env
      - redis_data:/data
    env_file:
      - ./env/redis/.env
      - ./.env

  etl_postgres_to_elastic:
    build:
      context: ./etl_postgres_to_elastic
      dockerfile: Dockerfile.dev
    volumes:
      - ./env:/env
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./env/api/.env
      - ./env/postgres/.env
      - ./env/redis/.env
      - ./env/docker/.env
      - ./env/elasticsearch/.env

  api:
    build:
      context: ./fastapi/src
      dockerfile: Dockerfile
    volumes:
      - ./env:/env
      - ./.env:/.env
      - ./fastapi/src:/src
    expose:
      - ${API_PORT}
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - etl_postgres_to_elastic
    env_file:
      - ./env/api/.env
      - ./env/postgres/.env
      - ./env/redis/.env
      - ./env/docker/.env
      - ./env/elasticsearch/.env
      - ./.env
  nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    env_file:
      - ./.env
    depends_on:
      - api
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:


